/**
 * Lablix service worker (generated by build.js — edit src/sw.template.js)
 * Precaches the whole game so it plays fully offline once loaded.
 */
const VERSION = '1790288569075';
const CACHE = 'lablix-' + VERSION;
const PRECACHE = [
    "./",
    "manifest.json",
    "css/styles.1790288569075.css",
    "js/game.1790288569075.js",
    "vendor/three.min.js?v=1790288569075",
    "img/logo.png",
    "img/icons/apple-touch-icon.png",
    "img/icons/icon-192.png",
    "img/icons/icon-512.png",
    "img/icons/maskable-512.png",
    "audio/music/background.mp3",
    "audio/fx/coin.mp3",
    "audio/fx/fall.mp3",
    "audio/fx/hit.mp3",
    "audio/fx/step.mp3",
    "audio/fx/wosh.mp3",
    "audio/taunts/it/after_hit_00.mp3?v=1790288569075",
    "audio/taunts/it/after_hit_01.mp3?v=1790288569075",
    "audio/taunts/it/after_hit_02.mp3?v=1790288569075",
    "audio/taunts/it/after_hit_03.mp3?v=1790288569075",
    "audio/taunts/it/after_hit_04.mp3?v=1790288569075",
    "audio/taunts/it/after_hit_05.mp3?v=1790288569075",
    "audio/taunts/it/after_hit_06.mp3?v=1790288569075",
    "audio/taunts/it/after_hit_07.mp3?v=1790288569075",
    "audio/taunts/it/after_hit_08.mp3?v=1790288569075",
    "audio/taunts/it/after_hit_09.mp3?v=1790288569075",
    "audio/taunts/it/after_hit_10.mp3?v=1790288569075",
    "audio/taunts/it/after_hit_11.mp3?v=1790288569075",
    "audio/taunts/it/after_hit_12.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_2_00.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_2_01.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_2_02.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_2_03.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_3_00.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_3_01.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_3_02.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_3_03.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_3_04.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_3_05.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_3_06.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_4_00.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_4_01.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_4_02.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_4_03.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_4_04.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_4_05.mp3?v=1790288569075",
    "audio/taunts/it/difficulty_increase_4_06.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_00.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_01.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_02.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_03.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_04.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_05.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_06.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_07.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_08.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_09.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_10.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_11.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_12.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_13.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_14.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_15.mp3?v=1790288569075",
    "audio/taunts/it/edge_proximity_16.mp3?v=1790288569075",
    "audio/taunts/it/fall_off_edge_00.mp3?v=1790288569075",
    "audio/taunts/it/fall_off_edge_01.mp3?v=1790288569075",
    "audio/taunts/it/fall_off_edge_02.mp3?v=1790288569075",
    "audio/taunts/it/fall_off_edge_03.mp3?v=1790288569075",
    "audio/taunts/it/fall_off_edge_04.mp3?v=1790288569075",
    "audio/taunts/it/fall_off_edge_05.mp3?v=1790288569075",
    "audio/taunts/it/fall_off_edge_06.mp3?v=1790288569075",
    "audio/taunts/it/fall_off_edge_07.mp3?v=1790288569075",
    "audio/taunts/it/fall_off_edge_08.mp3?v=1790288569075",
    "audio/taunts/it/final_death_00.mp3?v=1790288569075",
    "audio/taunts/it/final_death_01.mp3?v=1790288569075",
    "audio/taunts/it/final_death_02.mp3?v=1790288569075",
    "audio/taunts/it/final_death_03.mp3?v=1790288569075",
    "audio/taunts/it/final_death_04.mp3?v=1790288569075",
    "audio/taunts/it/final_death_05.mp3?v=1790288569075",
    "audio/taunts/it/final_death_06.mp3?v=1790288569075",
    "audio/taunts/it/final_death_07.mp3?v=1790288569075",
    "audio/taunts/it/final_death_08.mp3?v=1790288569075",
    "audio/taunts/it/final_death_09.mp3?v=1790288569075",
    "audio/taunts/it/final_death_10.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_00.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_01.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_02.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_03.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_04.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_05.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_06.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_07.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_08.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_09.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_10.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_11.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_12.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_13.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_14.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_15.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_16.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_17.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_18.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_19.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_20.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_21.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_22.mp3?v=1790288569075",
    "audio/taunts/it/general_mockery_23.mp3?v=1790288569075",
    "audio/taunts/it/near_death_00.mp3?v=1790288569075",
    "audio/taunts/it/near_death_01.mp3?v=1790288569075",
    "audio/taunts/it/near_death_02.mp3?v=1790288569075",
    "audio/taunts/it/near_death_03.mp3?v=1790288569075",
    "audio/taunts/it/near_death_04.mp3?v=1790288569075",
    "audio/taunts/it/near_death_05.mp3?v=1790288569075",
    "audio/taunts/it/near_death_06.mp3?v=1790288569075",
    "audio/taunts/it/near_death_07.mp3?v=1790288569075",
    "audio/taunts/it/near_death_08.mp3?v=1790288569075",
    "audio/taunts/it/near_death_09.mp3?v=1790288569075",
    "audio/taunts/it/reckless_movement_00.mp3?v=1790288569075",
    "audio/taunts/it/reckless_movement_01.mp3?v=1790288569075",
    "audio/taunts/it/reckless_movement_02.mp3?v=1790288569075",
    "audio/taunts/it/reckless_movement_03.mp3?v=1790288569075",
    "audio/taunts/it/reckless_movement_04.mp3?v=1790288569075",
    "audio/taunts/it/reckless_movement_05.mp3?v=1790288569075",
    "audio/taunts/it/reckless_movement_06.mp3?v=1790288569075",
    "audio/taunts/it/reckless_movement_07.mp3?v=1790288569075",
    "audio/taunts/it/reckless_movement_08.mp3?v=1790288569075",
    "audio/taunts/it/reckless_movement_09.mp3?v=1790288569075",
    "audio/taunts/it/sample_bella.mp3?v=1790288569075",
    "audio/taunts/it/sample_tosca.mp3?v=1790288569075",
    "audio/taunts/it/sample_tosca_v2.mp3?v=1790288569075"
];

self.addEventListener('install', (event) => {
    event.waitUntil(
        caches.open(CACHE).then((cache) =>
            cache.addAll(PRECACHE.map((url) => new Request(url, { cache: 'reload' })))
        )
    );
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys()
            .then((keys) => Promise.all(keys.filter((k) => k.startsWith('lablix-') && k !== CACHE).map((k) => caches.delete(k))))
            .then(() => self.clients.claim())
    );
});

self.addEventListener('message', (event) => {
    if (event.data === 'skipWaiting') self.skipWaiting();
});

// Media elements ask for byte ranges; answer them from the cached file
async function rangeResponse(request, response) {
    const buf = await response.arrayBuffer();
    const m = /bytes=(\d*)-(\d*)/.exec(request.headers.get('range') || '');
    const size = buf.byteLength;
    let start = m && m[1] ? parseInt(m[1], 10) : 0;
    let end = m && m[2] ? parseInt(m[2], 10) : size - 1;
    if (m && !m[1] && m[2]) { start = Math.max(0, size - parseInt(m[2], 10)); end = size - 1; }
    end = Math.min(end, size - 1);
    if (start >= size || start > end) {
        return new Response(null, { status: 416, headers: { 'Content-Range': `bytes */${size}` } });
    }
    return new Response(buf.slice(start, end + 1), {
        status: 206,
        headers: {
            'Content-Type': response.headers.get('Content-Type') || 'audio/mpeg',
            'Content-Range': `bytes ${start}-${end}/${size}`,
            'Content-Length': String(end - start + 1),
            'Accept-Ranges': 'bytes'
        }
    });
}

async function fromCache(request) {
    const cache = await caches.open(CACHE);
    return (await cache.match(request, { ignoreVary: true })) ||
        (await cache.match(request, { ignoreSearch: true, ignoreVary: true }));
}

self.addEventListener('fetch', (event) => {
    const request = event.request;
    if (request.method !== 'GET') return;
    const url = new URL(request.url);
    if (url.origin !== self.location.origin || !url.pathname.startsWith(new URL(self.registration.scope).pathname)) return;

    // Pages: network first (so updates arrive), cached copy when offline
    if (request.mode === 'navigate') {
        event.respondWith((async () => {
            try {
                const ctrl = new AbortController();
                const timer = setTimeout(() => ctrl.abort(), 4000);
                const res = await fetch(request, { signal: ctrl.signal });
                clearTimeout(timer);
                return res;
            } catch (e) {
                const cache = await caches.open(CACHE);
                return (await cache.match('./')) || (await cache.match('index.html')) || Response.error();
            }
        })());
        return;
    }

    // Everything else: cache first, network as a fallback
    event.respondWith((async () => {
        const cached = await fromCache(request);
        if (cached) return request.headers.has('range') ? rangeResponse(request, cached) : cached;
        return fetch(request);
    })());
});
